decide against unity. More semantically clear about the independence of each script if you just back them as separate scripts.

diff --git a/stampedIron b/stampedIron
--- a/stampedIron
+++ b/stampedIron
@@ -51,7 +51,27 @@ optional env dirs:
 "
 
 DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
-. ${DIR}/tools/_common.sh
+export IFS=''
+#-- common --
+
+error() { echo -e $@; exit 1; }
+usage() { [ "$1" ] && echo "error: $@"; error $USAGE_MSG; }
+dbg() {[ "$VERBOSE" ] && [ $VERBOSE -eq 1 ] && echo "$@"; $@; }
+is_int() { return [[ $1 =~ '^[0-9]+$' ]]; }
+mkdtmp() {
+    local -n l=$1;
+    if [ "$WORKDIR" ]; then
+       l="${WORKDIR}/`date +%s%N`"
+       mkdir -p $l
+    else
+        l=`mktemp -d 2>/dev/null || mktemp -d -t 'mytmpdir'`
+    fi
+}
+#layer of indirection to avoid returnvar scoping bug, see NOTES
+rcv() { local -n ret=$1; $2 ret "${@:3}"; }
+
+#-- /common --
+
 stampedIron=${DIR}
 d_tools=${DIR}/tools
 cookbook=$stampedIron/examples/recipes
